-- MySQL Script generated by MySQL Workbench
-- sáb 22 fev 2020 11:17:12 -03 - Fabiuskcomp
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema alienspace
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema alienspace
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alienspace` DEFAULT CHARACTER SET latin1 ;
USE `alienspace` ;

-- -----------------------------------------------------
-- Table `alienspace`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alienspace`.`USUARIO` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `alienspace`.`TAREFA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alienspace`.`TAREFA` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `tipo` ENUM('afazer', 'fazendo', 'feito') NULL DEFAULT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `descricao` (`descricao` ASC),
  INDEX `user_id` (`user_id` ASC),
  CONSTRAINT `TAREFA_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `alienspace`.`USUARIO` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 126
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `alienspace`.`TRANSACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alienspace`.`TRANSACAO` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `local` VARCHAR(255) NULL DEFAULT NULL,
  `valor` DECIMAL(8,2) NULL DEFAULT NULL,
  `mes` VARCHAR(15) NULL DEFAULT NULL,
  `ano` ENUM('2020', '2021', '2022', '2023', '2024') NOT NULL,
  `tipo` ENUM('Gasto', 'Saldo') NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC),
  CONSTRAINT `TRANSACAO_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `alienspace`.`USUARIO` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
